// try {
// console.log(sum(2, 5));
// let out2 = sum("2", 5);

// for (let i = 0; i <= out2; i++) {
//   console.log(i);
// }
// } catch (e) {
//   console.log(e);
// }

// function sum(a, b) {
//   if (typeof a != "number") {
//     throw "a is not a number";
//   }
//   return a + b;
// }

// // try {
// //    // statement which can have some exception

// // } catch(e) {
// //   // handle the exception
// // }

// if(condition) {

// } else {

// }
